name = "NCEI"
uuid = "1f554e9c-ddc6-5d78-a4ef-ff7defcf835d"
keywords = ["API", "Interface", "NOAA", "Weather", "Climate", "Data", "NCEI"]
license = "ISC"
authors = ["José Bayoán Santiago Calderón <naoyabpr@gmail.com>"]
description = "Interface for the National Centers for Environmental Information (NCEI) API"
doi = "10.5281/zenodo.1210010"
repository = "https://github.com/Nosferican/NCEI.jl.git"
version = "1.1.2"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"

[compat]
DataFrames = "1"
HTTP = "1"
JSON3 = "1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
